import numpy as np
a=np.tile(np.arange(0,40,60), (3,2))
print(a)
print("****************")
a=a.T
print(a)
a=np.array([[1,2,3],[4,5,6]])
a.ravel()
print(a)
a=np.array([[1,2,3],[4,5,6]])
a.ravel()
# b=a.ravel()
b=b.reshape((2,3))
print(a)
print(b)
print(a.shape)
a=np.zeros((3,2))
b=a.T.reshape(3*2)
b[0]=50
print(a)
print(b)
a=np.zeros((3,2))
b=a.T.reshape(3*2)
b[0]=50
print(a)
print(b)